select * 
from employees;

SELECT 
  -- Calculate attrition rate by dividing terminated employees by total employees and multiply by 100 for percentage
  COUNT(CASE WHEN EMPLOYMENT_STATUS ILIKE 'terminated' THEN 1 END) * 100.0 / COUNT(*) AS ATTRITION_RATE
-- Get data from employees table
FROM SI_HR_DEMO.PUBLIC.EMPLOYEES;

SELECT 
  EMPLOYMENT_STATUS,
  COUNT(*) AS TOTAL_EMPLOYEES,
  SUM(CASE WHEN p.PROMOTED = TRUE THEN 1 ELSE 0 END) AS TOTAL_PROMOTIONS,
  (SUM(CASE WHEN p.PROMOTED = TRUE THEN 1 ELSE 0 END) * 100.0 / COUNT(*)) AS PROMOTION_RATE,
  (SUM(CASE WHEN p.PERFORMANCE_RATING ILIKE '%MEETS%' OR p.PERFORMANCE_RATING ILIKE '%EXCEEDS%' THEN 1 ELSE 0 END) * 100.0 / COUNT(*)) AS PERCENT_MEETING_EXPECTATIONS
FROM SI_HR_DEMO.PUBLIC.EMPLOYEES e
LEFT JOIN SI_HR_DEMO.PUBLIC.EMPLOYEE_PERFORMANCE p
  ON e.EMPLOYEE_ID = p.EMPLOYEE_ID
GROUP BY EMPLOYMENT_STATUS;